### ISSUE TITLE
Serverside Subscriptions

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#1541]
Serverside Subscriptions is a way to get notified when data changes.

In the beginning we will support invoking a webhook, but in the future we will support targets such as AWS Lambda, Kinesis, Kafka, AMQP.

## Configuring a serverside subscription

Serverside subscriptions are configured in the graphcool.yml file

```yml
service: my-service

stage: ${env:GRAPHCOOL_STAGE}
secret: ${env:GRAPHCOOL_SECRET}
cluster: ${env:GRAPHCOOL_CLUSTER}

datamodel: database/datamodel.graphql

subscriptions:
  userChangedEmail:
    webhook:
      url: http://example.org/sendSlackMessage
      headers:
        Content-Type: application/json
        Authorization: Bearer cha2eiheiphesash3shoofo7eceexaequeebuyaequ1reishiujuu6weisao7ohc
    query: { ... }
```
