### ISSUE TITLE
Support multiple prisma databases in one project

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma1#1622]
I'd like to use two different Prisma databases in one project. This is currently not possible, because of:

- [ ] The logic used to find the project in .graphqlconfig. This needs to be updated to look for the same prisma.yml file that is used for the deployment.

- [ ] The logic the CLI uses to find the prisma.yml. If I want to deploy either one of my projects, I should run the `prisma deploy` command from the subfolder with the prisma.yml for that service.

So given the following folder structure:
```
|- db1
|    |- prisma.yml
|- db2
|    |- prisma.yml
```
And the following .graphqlconfig:
```yaml
projects:
  myFirstService:
    schemaPath: 'src/generated/db1.graphql
    extensions:
        prisma: db1/prisma.yml
  mySecondService:
    schemaPath: 'src/generated/db2.graphql
    extensions:
        prisma: db2/prisma.yml
```

Note that in this example, I deliberately used different project names. If it's easier to implement by using the convention 'project name == folder name' (so a project db1 always lives in the db1 folder), that's also fine with me.
