### ISSUE TITLE
add createMany mutation

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2160]
# Feature Request

A `createManyXs` mutation to create many nodes in a batched fashion.

Suggested API:

```graphql
mutation {
  createManyItems(data: [{
    name: "Tesla"
    price: "1000"
  }, {
    name: "Audi"
    price: "2"
  }]) {
    ids # list of ids for newly created nodes 
    count
  }
}
```

**Comment by codepunkt** [comment]
Where would i look in order to implement this?
After all, most of the groundwork for this seems done and things like `TypeCreateManyInput` already exist when you create nested resources.

I tried to find "CreateManyInput" via code search, but turned up empty-handed. Not sure if i was even searching the right repo.

**Comment by marcosfede** [comment]
any updates on this feature?

**Comment by ellipticaldoor** [comment]
Is hard to implement? I think this will be very useful.

**Comment by FluorescentHallucinogen** [comment]
Any progress?

**Comment by marcosfede** [comment]
Are there plans to tackle this any time soon? Or at least some help from the prima team as to how it should be tackled for contributors to work on this?

**Comment by devuxer** [comment]
I'm missing not having this after 3 hours of trying out Prisma.

**Comment by lnmunhoz** [comment]
Hey guys? This looks pretty simple to implement since Prisma already have updateMany. What are the blockers?

**Comment by andrejunges** [comment]
any updates on this?

**Comment by faurehu** [comment]
Do we have any workarounds for this?

**Comment by kevrat** [comment]
It would be very handy

**Comment by Swoorup** [comment]
one of the first thing I am using prisma is the bulk import of csv rows, so bit saddened by unpresence of this feature

**Comment by george1028** [comment]
I need this. Please hurry up

**Comment by rollrodrig** [comment]
I need it tooooo :(

**Comment by gotexis** [comment]
bump

**Comment by vladimirvolek** [comment]
any good workaround for this?

**Comment by mpcen** [comment]
I feel like this is such a must-have. Shame it wasn't added way sooner

**Comment by HugoLiconV** [comment]
any updates on this?

**Comment by aarshaw** [comment]
does anyone have a good workaround for this?

**Comment by mpcen** [comment]
It isn't pretty but I'm temporarily getting around it by building a dynamic template string that prepends an arbitrary unique ID to each data object getting inserted and calling the mutation method. Using axios for the POST, It looks something like this:

```
const players = [{id: 'a', name: 'playerA'}, {id: 'b', name: 'playerB'}]
let playerMutations = ``;

players.forEach(player => {
    playerMutations += `
        p_${player.id}: createPlayer (
            data: {
                name: "${player.name}"
            }
        ) {
            name
        }
    `;
});

const mutation = `
    mutation {
        ${playerMutations}
    }
`;

try {
    await axios({
        url: 'http://localhost:4000/default/dev',
        method: 'post',
        data: { query: mutation }
    });
} catch (e) {
    console.error('Error in PlayerServices run:', e.message);
    return [];
}
```

**Comment by mpcen** [comment]
@aarshaw check out my comment above

**Comment by mpcen** [comment]
@vladimirvolek @HugoLiconV @gotexis @george1028 @rollrodrig check out my comment above. temp solution that im currently using

**Comment by vladimirvolek** [comment]
You can use raw access (edit prisma config `rawAccess: true`). This option provides `$graphql` function where you can _insert many values in a single request_.

_docker-compose.yml_
```
PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            port: 3306
            rawAccess: true // HERE
            migrations: true
```

_generated/prisma-client/index_
```
export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;
```

**Resources**
https://www.prisma.io/forum/t/how-i-can-create-many-records-at-the-same-time-with-the-prisma-client/4723/4
https://github.com/prisma/prisma/issues/3300#issuecomment-430696015
