### ISSUE TITLE
Initializing Prisma + Database at once might result in undefined behaviour

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2315]
# Bug Report

**Current behavior**

run `docker-compose up -d` with this:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
```

Sometimes, the Prisma container will be "faster" than the MySQL container. Then the DB refuses to be connected to, and the Prisma container runs into undefined behaviour.

**Expected behavior?**

Be super resilient about weird edge cases similar to the one described above.
