### ISSUE TITLE
Support PostgreSQL schemas

### ISSUE THREAD

**Issue by mytototo** [prisma/prisma1#2477]
# Feature Request

**What feature are you missing?**
It would be nice for the PostgreSQL connector to support schemas, so we can create a GraphQL API from an existing database with multiple schemas. This is the only missing feature for me to move forward with Prisma. If such a feature already exists, please excuse me for the mistake but I can't find any docs about it.

**How could this feature look like in detail? Tradeoffs?**
This could look like this:
```gql
type User @pgTable(name: "mySchema.users") {
  id: ID! @unique
  email: String! @unique
  name: String!
}
```

Or like this:
```gql
type User @pgSchema(name: "mySchema") @pgTable(name: "users") {
  id: ID! @unique
  email: String! @unique
  name: String!
}
```

Or something like this:
```gql
type User @pgTable(schema: "mySchema", name: "users") {
  id: ID! @unique
  email: String! @unique
  name: String!
}
```

Maybe to support this feature we'd also need some requirements in the environment? Since I don't know the internals of Prisma I don't know if it's needed or not.
```yml
version: "3.1"

services:
  #...
  prisma:
    image: "prismagraphql/prisma:1.8"
    restart: "unless-stopped"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: "postgres"
            host: "database"
            port: 5432
            user: "user"
            password: "password"
            migrations: false
            database: "mydatabase"
            schemas:
              - "mySchema"
    ports:
      - "4466:4466"

volumes:
  postgres:
```
