### ISSUE TITLE
Deploy Prisma Server to Now (docker support)

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2501]
# Feature Request

We should investigate what the missing steps are for supporting [deploying Prisma servers as a Docker app to Zeit now](https://zeit.co/docs/deployment-types/docker)

**Comment by develomark** [comment]
@marktani 

I had this working well with now up until recently when you added in metrics support.

Simply copied across a yml file with the prisma config in the `dockerfile`:

```
FROM prismagraphql/prisma:1.12-alpha
ARG PRISMA_CONFIG_PATH
ENV PRISMA_CONFIG_PATH prisma.yml
COPY config.yml prisma.yml
EXPOSE 4466
```
The local file config.yml contains the following:

```
managementApiSecret: PRISMA_MANAGEMENT_API_SECRET
port: 4466
databases:
    default:
        connector: mysql
        host: SQL_HOST
        port: SQL_PORT
        user: SQL_USER
        password: SQL_PASSWORD
        migrations: true
        active: true
```

The main issue preventing this from being used in production is that currently Now does not seem to be passing any environment variables to the docker build.

https://github.com/zeit/now-cli/issues/522
https://github.com/zeit/now-cli/issues/1446

Once they have fixed that you could then pass `SQL_PASSWORD` and `PRISMA_MANAGEMENT_API_SECRET` as environment vars.
e.g:
```
RUN sed -i s/SQL_PASSWORD/$SQL_PASSWORD/g prisma.yml
```

___

Ideally, we would want to pass the entire Prisma configuration as a single environment var, but Now does not support base64. See https://github.com/zeit/now-cli/issues/749.
