### ISSUE TITLE
Prisma Horizontal Scaling

### ISSUE THREAD

**Issue by mcmar** [prisma/prisma1#2850]
**Describe the bug**
When I try to scale Prisma horizontally by adding a second server, the first server logs:
```
Obtaining exclusive agent lock...
Obtaining exclusive agent lock... Successful.
```
then the second server logs just this and crashes:
```
Obtaining exclusive agent lock...
```

The reason appears to be this line of code:
https://github.com/prismagraphql/prisma/blob/d5c97fe8f1c1ee223ec1392ebdf16f2545b2f763/server/servers/deploy/src/main/scala/com/prisma/deploy/migration/migrator/DeploymentSchedulerActor.scala#L52

It seems that Prisma is explicitly ensuring that there's only ever 1 cluster/server (prisma terminology changes) that can run against a DB.

**To Reproduce**
1. Initialize Prisma server from Prisma AWS Fargate template (https://github.com/prismagraphql/prisma-templates/tree/master/aws)
2. Go to ECS cluster (name will be what you used during CF stack creation
3. Click on `Prisma` service
4. Click Update in top-right corner
5. Increase `Number of tasks ` from 1 to 2
6. Click Next, Next, Next, and Done

**Expected behavior**
2 Prisma instances would run against 1 DB

**Screenshots**
None

**Versions (please complete the following information):**
 - OS: Irrelevant, it's in AWS 
 - `prisma` CLI: `prisma/1.11.1 (darwin-x64) node-v8.11.1`
 - Prisma Server: `1.11.0` (per Cloudformation template)

**Additional context**
Already reported in the slack channel. Was told to create a bug here.
@divyenduz

**Comment by terijyu** [comment]
+1, encountering this problem as well

**Comment by mavilein** [comment]
Hey @mcmar ,

thanks for bringing this up. This is an area where we are lacking documentation. The prisma server can be started either with the mangement API enabled or not. If the management API is enabled it will try to acquire the agent lock on startup. This is to ensure that there is only one Prisma server at a time writing into the management tables. So your second server also has the management API hence you are seeeing this log message.

The management API can be simply enabled in the Prisma server config, e.g.:
```yaml
port: 60000
managementApiSecret: my-secret
rabbitUri: amqp://my-rabbitmq-server
enableManagementApi: true|false
databases:
  default:
    connector: mysql
    ...
```

In Prisma Cloud we are running Prisma like this for horizontal scalability:
- Run **exactly 1** one Prisma server with the Management API enabled. Additionally run multiple Prisma servers with the Management API disabled. Internally we call those server types primary and secondary.
- Your load balancer in front of the servers must be setup like this:
  - All requests to `/management` must be routed to the primary server.
  - All other requests may be routed to any of the servers (primary + secondary).
- in addition to this you will also need a RabbitMQ server, which we use for PubSub. We need it to publish change events about the data to all servers so that they can notify connected subscriptions over Websocket. (see the config entry `rabbitUri` above). If you don't want to run a RabbitMQ server on your own, i recommend [CloudAMQP](https://www.cloudamqp.com/) as a hoster.

Does that help?

**Comment by mavilein** [comment]
@emmenko : Right now it is required. We need for RabbitMQ for those reasons:
1. as PubSub to power subscriptions over Websockets
2. to store ServerSideSubscriptions/Webhooks in a Queue. This allows us to eventually deliver Webhooks even if the Server goes down due a crash or reboot.
3. to propagate information about schema changes to all servers. We need this as each server holds a cache of the schema of service. Not having a cache would mean adding significant latency to query execution.

I guess you are fine with point 1. Point 2 is a tradeoff you need to decide for yourself in your usecase. point 3 is currently a blocker.

If we can find a solution for point 3 we could repackage the Prisma server without the RabbitMQ dependency. We could enable this through a separate Docker image or configuration flag.

**Comment by emmenko** [comment]
I see. So if I want multiple replicas I also need to have a rabbitmq cluster on the side.

Do you plan to make the pubsub system configurable or is rabbitmq the only option? For example, I’m running my services on GCP and it would be easier to use google pubsub.

Thanks anyway for the explanation! 🙏

**Comment by mcmar** [comment]
@mavilein Is Prisma using AMQP 0.9.1 or 1.0?
1.0 will work with Apache ActiveMQ and Amazon MQ, which would make my life much easier.
0.9.1 would require me to spin up my own RabbitMQ service with its own ELB.

**Comment by mavilein** [comment]
@emmenko : RabbitMQ is currently the only option, but we have encapsulated our pubsub code into a neat interface. We could provide additional implementations for e.g. google pubsub. I just added a Feature request for this.

@mcmar : We are using the RabbitMQ Java client, so i think this 0.9.1 then.

@mcmar @emmenko : Would you be happier if we would support Apache Kafka? We are considering to add it for another feature anyway.

**Comment by emmenko** [comment]
Thanks. For now I'm trying using the `stable/rabbitmq` helm chart. I think it should be fine.
In our specific case, we run our services on K8s on Google Cloud, so for us an integration with Google PubSub would be perfect so that we don't have to manage that on our own 😉

**Comment by emmenko** [comment]
@mavilein I'm trying to deploy prisma with 1 primary and 2 secondary. The primary has the managementApi enabled, the secondaries do not.

However, after starting, the primary and one the secondary keep crashing with the error

```bash
Fatal error during deployment worker initialization: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://single-server/user/$b#-844349262]] after [300000 ms]. Sender[null] sent message of type "com.prisma.deploy.migration.migrator.DeploymentProtocol$Initialize$".
```

I noticed that all 3 prisma containers are trying to "obtain the agent lock". From what you wrote before I tought that only the primary is suppose the get the lock, or should all of them do it? In that case, any idea why am I still getting errors? 🤔

I'm using `prisma:1.13.4`.

**Comment by emmenko** [comment]
Now the primary and one of the secondary are running but the 2nd secondary keeps crashing (no errors in the logs, only 👇)

```bash
Obtaining exclusive agent lock...
Initializing workers...
Successfully started 1 workers.
Server running on :4466
Version is up to date.
```

Am I doing something wrong? 🤔

**Comment by emmenko** [comment]
Tried also with 1 primary and 1 secondary. After a couple of min, the secondary crashed with the same error.

**Comment by emmenko** [comment]
I have a feeling that the management API is still enabled in both. I checked and I'm passing `enableManagementApi: true` to the primary and `enableManagementApi: false` to the secondary.

**Comment by emmenko** [comment]
In case it helps, here are the logs for the pods (for the timings)

```bash
$ kubectl get pods -w | grep prisma
prisma-primary-c6f64d69d-ckkbn          2/2       Running   0          3m
prisma-secondary-75b857b766-xx8jz       2/2       Running   0          3m
prisma-secondary-75b857b766-xx8jz   1/2       Error     0         6m
prisma-secondary-75b857b766-xx8jz   1/2       Running   1         6m
prisma-secondary-75b857b766-xx8jz   2/2       Running   1         8m
```

And here the logs for the primary

```bash
Obtaining exclusive agent lock...
Obtaining exclusive agent lock... Successful.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
Deployment worker initialization complete.
Initializing workers...
Successfully started 1 workers.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
Server running on :4466
Version is up to date.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.
```

and here for the secondary

```bash
Obtaining exclusive agent lock...
Initializing workers...
Successfully started 1 workers.
Server running on :4466
Version is up to date.
Fatal error during deployment worker initialization: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://single-server/user/$b#-1603503801]] after [300000 ms]. Sender[null] sent message of type "com.prisma.deploy.migration.migrator.DeploymentProtocol$Initialize$".
```

**Comment by emmenko** [comment]
I noticed that when I try to access on both containers the `http://localhost:4466/management` I get the graphql playground. Is this supposed to be working even if the `enableManagementApi` is set to false?

**Comment by mavilein** [comment]
@emmenko : Oh my bad. I forgot to say that you need to use `prisma-prod` image. Only this one contains the necessary ifs. We should really improve this experience. Thx for keeping to dig 👍

**Comment by emmenko** [comment]
> I forgot to say that you need to use `prisma-prod` image

Ooooh, thanks! 😇

I'll try that right away.

Btw, I'm happy to contribute to the documentation feedback with the experience I had so far. Let me know in case you need that 😉

**Comment by emmenko** [comment]
Works! 🙌

```bash
$ kubectl get pods -w |grep prisma
prisma-rabbitmq-0         1/1       Running   0          4h
prisma-rabbitmq-1         1/1       Running   0          4h
prisma-rabbitmq-2         1/1       Running   0          4h
prisma-primary-56d5699664-sn2sj         2/2       Running   0          35m
prisma-secondary-cbb5c87b8-c8qdn        2/2       Running   0          27m
prisma-secondary-cbb5c87b8-z8zgh        2/2       Running   0          23m
```

**Comment by mavilein** [comment]
@emmenko : Nice. 🎉 
I have opened an [issue](https://github.com/prismagraphql/prisma/issues/2869) to unify our 2 Docker images as they do not seem necessary to me and just cause confusion.
Happy to come back to you to get your feedback on the docs when we have a first version ready! 🙏

**Comment by mcmar** [comment]
@mavilein I'm attempting to implement the pattern you described in which you route `/management` to primsa-primary and all other routes `*` to prima-primary and prisma-secondary.
I'm unable to implement that pattern in AWS using Application Load Balancers because ECS services can only register themselves in one target group.
I'm working off of the fargate.yml template in the `prisma-templates` repo.
How does prisma host their own servers in AWS? Do you use ECS? Do you have 2 separate prisma services? Do you use Application Load Balancers as opposed to Classic Load Balancers? I can't find a way to implement it using ECS with ALBs.

**Comment by mcmar** [comment]
Hey @emmenko if you have a fairly generic kubernetes template for prisma with support for horizontal scaling, would you mind posting it or submitting a PR against https://github.com/prismagraphql/prisma-templates ?
The current docs only show the single-server setup.
I'm currently working on adding a second Cloudformation template for horizontal scaling. It'd be good to get something in there for Kubernetes too.
I thought it'd be cool if we could all contribute back what we're learning and grow the OSS community around Prisma.

**Comment by emmenko** [comment]
@mcmar hey, sure thing! I’ll start working on that in the next days 👌

**Comment by develomark** [comment]
Handy thread. Thank you for the information. I'd like to cast my vote for Google PubSub also as we currently have a cloud function consuming Prisma subscriptions over HTTP and passing them into GCP PubSub. This would reduce the latency.

**Comment by lethot** [comment]
@emmenko @mavilein hi, I'm in the same situation, I'm a bit confused, I'm stuck at the prisma-prod image step,
when I try to run the container with this image, I get an error like I'm missing some SQL_INTERNAL_PASSWORD env var. I'm using cloud sql postgres and I can't find where I missed something and what this var is.

**Comment by emmenko** [comment]
Where are you running the containers? Kubernetes?

**Comment by lethot** [comment]
@emmenko kubernetes engine yes

**Comment by lethot** [comment]
here is my config
```yaml
- name: PRISMA_CONFIG
          value: |
            port: 4466
            rabbitUri: amqp://...
            managementApiEnabled: false
            databases:
              default:
                connector: postgres
                host: 127.0.0.1
                port: 5432
                user: "$(PG_USERNAME)"
                password: "$(PG_PASSWORD)"
                migrations: true
                connectionLimit: 4
```

**Comment by lethot** [comment]
with the 'prismagraphql/prisma:1.14' image the container is ok but I has the exclusive agent lock problem and the container restart every 5min
with the  'prismagraphql/prisma-prod' image the container don't even start and fire the missing var SQL_INTERNAL_PASSWORD error

by the way thanx for your help

**Comment by lethot** [comment]
😱thanx you just make me realized that I forgot the tag on the prisma-prod image !!! 
Yes I plan to to the same for management and replicas

**Comment by mcmar** [comment]
Hi @emmenko, would you be able to post your kubernetes templates that you're using with prisma-prod and horizontal scaling? It looks like the current kubernetes instructions for prisma don't include rabbitMQ or horizontal scaling 😢
https://www.prisma.io/docs/tutorials/cluster-deployment/kubernetes-aiqu8ahgha

**Comment by mcmar** [comment]
@mavilein @divyenduz Can anyone on the Prisma team please provide a working template with horizontal scaling? Could be Cloudformation or K8s or anything. I've been trying for months to get this working, but I've got nothing. I documented the issue I'm having with ECS. I'd appreciate any help.

**Comment by dpetrick** [comment]
I whipped together a quick guide based on experiments I did myself with Kubernetes. Give it a try and tell me if it works for you. https://github.com/dpetrick/prisma-k8s-example

**Comment by develomark** [comment]
Hi @emmenko, I wonder how are you progressing with the GCP kubernetes templates?

**Comment by emmenko** [comment]
Hey guys, I ended up writing an article on how we did it in my team because it's a bit difficult to come up with something generic that fits all use cases.

https://techblog.commercetools.com/prisma-horizontal-scaling-a-practical-guide-3a05833d4fc3

Have a read and hopefully it's somehow helpful to a lot of people 😊

**Comment by jhalborg** [comment]
Scaling Prisma horizontally right now seems to require quite a bit of DevOps knowledge. For DevOps novices such as myself, is there any hope that this will be made easier in Prisma sometime soonish? I notice that this issue is tagged with `docs` and not with `feature` 😳

**Comment by mavilein** [comment]
@jhalborg : As a first step we will improve the docs and then follow up with some changes to make it significantly easier to run Prisma in production. We will make RabbitMQ optional if you don't use subscriptions for example. Thanks for letting us know! 🙏

**Comment by jhalborg** [comment]
@mavilein - Thanks! But what about simply scaling Prisma servers horizontally with no subscriptions - is that possible to do somewhat easily?

As far as I understand, if I i.e. deploy to Heroku and scale up more dynos, that won't work seeing as it needs a master/slave setup for propogating changes from the `/management` endpoint, correct?

**Comment by emmenko** [comment]
> As far as I understand, if I i.e. deploy to Heroku and scale up more dynos

Well it's not really a ~~master/slave~~ (primary/secondaries).
You can deploy and scale up the servers that are configured without the `/management` endpoint.
Then have separately a single server with the `/management` API enabled.

Without the RabbitMQ dependency coming up, things are going to be a bit easier to set up and manage hopefully. Looking forward to that!

**Comment by jhalborg** [comment]
To be honest, I'm still very confused. Perhaps I'll just have to wait on new docs and see if that helps. 

As it stands now, Prisma seems to be the weakest link in our setup. The API scales horizontally automagically, but that doesn't help much when it needs to hit a single Prisma server to access the DB.

**Comment by mcmar** [comment]
@jhalborg For heroku, you would do 3 things:
1) Use a [rabbitMQ heroku addon](https://elements.heroku.com/addons/cloudamqp)
2) Change the `prisma` docker image to `prisma-prod`
3) Add the `rabbitUri: amqp://...` and `managementApiEnabled: false` props to your `PRISMA_CONFIG` env var.

**Comment by jhalborg** [comment]
Thanks @mcmar - I might be slow, but I'm still unsure, I haven't worked with RMQ before. If I set those two variables in my config, where would the management API (primary server) then be hosted? And will it "just work" if I setup that addon and refer to it in the config?

**Comment by emmenko** [comment]
I'm not much familiar with Heroku to be able to help you out further. Maybe someone who does can jump in?
Have you also try asking for help in the Slack channels?

**Comment by kylemclaren** [comment]
@jhalborg have you seen [this article](https://github.com/prisma/prisma/issues/2850#issuecomment-432298548)? It's quite in-depth and should give you a good foundation if you are willing to work through it step-by-step.

I don't think Heroku is a great place to deploy the Prisma API server unless you only plan on running a single dyno. If you're not able to set this all up then perhaps you're a good candidate for Prisma Cloud.

**Comment by mcmar** [comment]
@jhalborg I didn't provide instructions for the primary server. If you want to also host that in Heroku, then you would clone your Heroku environment and go through these steps:
1) Copy your `CLOUDAMQP_URL ` (or similar name) env var from above. DO NOT create a new rabbitMq plugin. They need to point to the same server.
2) Change the prisma docker image to prisma-prod (same as above)
3) Add the `rabbitUri: amqp://...` and `managementApiEnabled: true` props to your PRISMA_CONFIG env var.
4) Only spin up one server for primary.

**Comment by xcv58** [comment]
I try to reproduce the horizontal scale on localhost. But it seems no message send to RabbitMQ. Here is the docker-compose.yml file: https://github.com/xcv58/Prisma-Horizontal-Example/blob/master/docker-compose.yml

Could you please point out what's wrong with the configuration? Thanks!

**Comment by Siyfion** [comment]
Do people/@emmenko not still see issues when doing Prisma version updates? As most K8s / ECS setups will provision the new “management enabled“ instance in parallel before turning off the old one? Won’t that cause a lock and error?

**Comment by emmenko** [comment]
Hmm, as far as I remember that’s not a problem because the management pod is actually not strictly necessary for the runtime functionality. For example, you could only spin up a prisma instance with the management API enabled only when you need to perform management tasks, after that you could shut it down. Of course there should be other prisma instances running (without the management API).
The lock is only relevant to ensure that only 1 instance of the management API is active.

Hope that clarify your question. Also, if I explained something wrong, please someone correct me.

**Comment by smojtabai** [comment]
Hi, I don't know a ton about rabbitmq but I was just trying to set this up to see if I can get it to work but I am currently getting this error:

[ERROR] [05/04/2019 03:38:01.835] [single-server-akka.actor.default-dispatcher-5] [akka://single-server/user/subscriptions-manager] Unable to declare rabbit exchange: java.io.IOException

I just setup the free cloudamqp server and set the url in the config to the following:

amqp://vedlltma:<PASSWORD>@crocodile.rmq.cloudamqp.com/vedlltma

Is there anything about the free version or something I need to setup to get this to work? I am using prisma-prod image 1.31.0.

Any help would be greatly appreciated, thanks!

prisma config overall looks like:

```
port: 60000
                managementApiSecret: SECRET
                enableManagementApi: true
                rabbitUri: amqp://vedlltma:PASSWORD@crocodile.rmq.cloudamqp.com:5671
                databases:
                  default:
                    connector: postgres
                    host: nodabl-backend-staging.crkrwrfdc1df.us-east-1.rds.amazonaws.com
                    port: 5432
                    user: prisma_service
                    password: SECRET
                    migrations: true
```

**Comment by priley86** [comment]
after reading the docs on prisma2, i don't quite follow if this issue is remediated? It seems that Photon will generate a type safe client, but still uses the prisma binary exposed here for database access. Is it to be assumed that this binary is by itself horizontally safe (if it were to target the same connection)?

Otherwise, is the workaround described above still suggested for prisma2?

**Comment by yashlogic** [comment]
I am deploying prisma on ecs with a manager and worker services. When I scale worker service from 1 to >1. It is showing below message in logs.

I am running prismagraphql/prisma-prod:1.34.8 image with ecs rabbitmq cluster.

```sh
[INFO] [09/09/2019 06:24:48.310] [single-server-akka.actor.default-dispatcher-7] [akka://single-server/user/$g] Message [akka.actor.Status$Success] without sender to Actor[akka://single-server/user/$g#850926587] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

and also subscription started skip new messages.

**Comment by jerilcj1** [comment]
I am trying to install prisma rabbitmq on a kubernetes cluster but I am getting this error which says "Unable to declare rabbit exchange".

This is the connection string that I use for rabbitmq

amqp://user:ypvibil8QM@rabbitmq.default.svc.cluster.local:5672

Please note: rabbitmq is installed as a helm chart. I have also provided my prisma deployment kubernetes file.

```
Caused by: java.lang.Exception: Unable to declare rabbit exchange: java.net.SocketTimeoutException
        at com.prisma.messagebus.utils.RabbitUtils$.declareExchange(RabbitUtils.scala:18)
        at com.prisma.messagebus.pubsub.rabbit.RabbitAkkaPubSub.<init>(RabbitAkkaPubSub.scala:36)
        at com.prisma.prod.PrismaProdDependencies.invalidationPubSub$lzycompute(PrismaProdDependencies.scala:78)
        at com.prisma.prod.PrismaProdDependencies.invalidationPubSub(PrismaProdDependencies.scala:75)
        at com.prisma.prod.PrismaProdDependencies.invalidationSubscriber$lzycompute(PrismaProdDependencies.scala:81)
        at com.prisma.prod.PrismaProdDependencies.invalidationSubscriber(PrismaProdDependencies.scala:81)
        at com.prisma.subscriptions.resolving.SubscriptionsManager.<init>(SubscriptionsManager.scala:58)
        at com.prisma.websocket.WebSocketHandler.$anonfun$subscriptionsManager$1(WebSocketHandler.scala:24)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:624)
        at akka.actor.ActorCell.create(ActorCell.scala:650)
        ... 9 more
Caused by: java.net.SocketTimeoutException
        at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:50)
        at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:60)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:911)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:870)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:828)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:996)
        at com.prisma.rabbit.PlainRabbit$.$anonfun$connect$1(PlainRabbit.scala:25)
        at scala.util.Try$.apply(Try.scala:209)
        at com.prisma.rabbit.PlainRabbit$.connect(PlainRabbit.scala:11)
        at com.prisma.rabbit.Rabbit$.channel(Queue.scala:21)
        at com.prisma.rabbit.Rabbit$.channel(Queue.scala:13)
        at com.prisma.messagebus.utils.RabbitUtils$.declareExchange(RabbitUtils.scala:11)
        ... 20 more

[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
[INFO] [02/24/2020 04:48:18.670] [single-server-akka.actor.default-dispatcher-9] [akka://single-server/system/IO-TCP/selectors/$a/1] Message [akka.io.Dns$Resolved] from Actor[akka://single-serve
r/system/IO-DNS/inet-address/$d#-1722408340] to Actor[akka://single-server/system/IO-TCP/selectors/$a/1#-615185858] was not delivered. [1] dead letters encountered. This logging can be turned of
f or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [02/24/2020 04:48:21.970] [single-server-akka.actor.default-dispatcher-4] [akka://single-server/system/IO-TCP/selectors/$a/0] Message [akka.io.Dns$Resolved] from Actor[akka://single-serve
r/system/IO-DNS/inet-address/$d#-1722408340] to Actor[akka://single-server/system/IO-TCP/selectors/$a/0#-2083961340] was not delivered. [2] dead letters encountered. This logging can be turned o
ff or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLException: Received close_notify during handshake
```

This is my kubernetes deployment file for prisma

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-deployment
  #namespace: prisma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma-primary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: prisma-primary
    spec:
      containers:
        - name: prisma-primary
          image: prismagraphql/prisma-prod:1.34
          imagePullPolicy: Always
          resources: # CHANGE THIS AS NEEDED
            requests:
              memory: "1Gi"
              cpu: "10m"
            limits:
              memory: "1Gi"
              cpu: "10m"
          env:
            - name: SLOW_QUERIES_LOGGING
              value: "true"
            - name: JAVA_OPTS
              value: "-Xmx800m" # CHANGE THIS AS NEEDED
              - name: ENV
              value: "prod"
            - name: PRISMA_CONFIG
              value: | # CHANGE THIS AS NEEDED
                port: 4466
                managementApiSecret: "MuchSecret"
                enableManagementApi: "true"
                server2serverSecret: "SuperSecretWow"
                rabbitUri: "amqp://user:ypvibil8QM@rabbitmq.default.svc.cluster.local:5672"
                databases:
                  default:
                    connector: mongo
                    uri: mongodb://mongodb-mongodb-replicaset.default.svc.cluster.local:5672
                    active: "true"
                    connectionLimit: 20
                    database: "prisma"
                    managementSchema: "prisma"
                    ssl: false
          ports:
            - containerPort: 4466
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-primary-service
  #namespace: prisma
spec:
  selector:
    app: prisma-primary
  type: ClusterIP
```
