### ISSUE TITLE
Client generation should respect prettier configuration

### ISSUE THREAD

**Issue by mxstbr** [prisma/prisma1#3531]
**Is your feature request related to a problem? Please describe.**
The generated Flow client uses different prettier settings than we do, so the diff is always pretty unreadable until you run prettier over it manually.

**Describe the solution you'd like**
The flow client generation should respect the prettier configuration in the nearest `.prettierrc` file if there is one.

**Describe alternatives you've considered**
- Add a `postgenerate` hook that allows one to run prettier over the generated client

**Comment by P4sca1** [comment]
Would also like to see prettier integration for the typescript client, similar to how graphqlgen handles this.

**Comment by chanlito** [comment]
I'm doing the following in `prisma.yml`:
```yml
hooks:
  post-deploy:
    - npx prisma generate
    - npx prettier server/generated/prisma-client/**/*.ts --config package.json --write

```
