### ISSUE TITLE
prisma generate throws an error if part of secret and endpoint came from a variable

### ISSUE THREAD

**Issue by plty** [prisma/prisma1#3659]
**Describe the bug**
`prisma generate` throws an error if part of secret and endpoint came from a variable

**To Reproduce**
Set this as prisma.yml
```
endpoint: https://internal.example.com/example-api/${self:custom.name}
datamodel: datamodel.graphql
secret: ${self:custom.endpoint-secret}

generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client/
  - generator: graphql-schema
    output: ../src/generated/prisma-client/

custom:
  endpoint-secret: ${env:PRISMA_ENDPOINT_SECRET}
  name: ${env:PRISMA_DEPLOYMENT_UID}
```

**Expected behavior**
`prisma generate` would still work

**Screenshots**
![screenshot from 2018-12-06 03-13-58](https://user-images.githubusercontent.com/10240857/49537867-12c73d00-f905-11e8-88a3-70d342984135.png)

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - `prisma` CLI: `prisma/1.22.1 (linux-x64) node-v11.2.0`]
 - Prisma Server: `v1.22`

**Additional Information**
`prisma deploy would still work`

**Comment by pantharshit00** [comment]
I was able to reproduce it, here is my output:

![image](https://user-images.githubusercontent.com/22195362/49579599-b69b0200-f972-11e8-8df1-86f9be9189cb.png)


Reproduction repository: https://github.com/pantharshit00/prisma-issue-3659

CLI version: prisma/1.22.1 (darwin-x64) node-v11.2.0

**Comment by chrisui** [comment]
I've encountered this when trying to get prisma working nicely in a local docker dev setup. Granted I'm a bit of a docker noob so struggling!

I have an app in one container and it needs to access prisma api via the hostname `prisma`. However on the host I need to run the playground which has to access via `localhost`. 

Is there a recommended approach for this?

**Comment by pantharshit00** [comment]
I can still reproduce with 1.30 @divyenduz

**Comment by pantharshit00** [comment]
I can still reproduce with 1.30 @divyenduz

**Comment by ZhengYuTay** [comment]
Faced the error as well, here's my config similar
```
custom:
  endpoint: http://localhost:4466/sample/${env:NODE_ENV, 'dev'}
  
datamodel: datamodel.prisma
generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client/
seed:
  run: ts-node ./prisma/seed.ts
hooks:
  post-deploy:
    - npx nexus-prisma-generate --client ./src/generated/prisma-client --output ./src/generated/nexus-prisma
endpoint: ${self:custom.endpoint}

```
