### ISSUE TITLE
Prisma deploys with different types, then specified inside datamodel

### ISSUE THREAD

**Issue by huv1k** [prisma/prisma1#3674]
**Describe the bug**
Prisma deploys different datamodel, then specified inside `datamodel.graphql`. 

**Reproduction**
Try to deploy with this datamodel:
```graphql
type Test {
  dates: [DateTime]
}
```
Deployment:
![](https://i.imgur.com/tBRbIQ2.png)

**Expected behavior**
Throw error, that `dates: [DateTime]` is not valid and suggest actual possible values. 

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - CLI: `prisma/1.24.0-alpha.2 (darwin-x64) node-v9.10.1`
 - Prisma Server:  `prismagraphql/prisma:1.23-alpha`

**Comment by pantharshit00** [comment]
I was unable to reproduce this in the latest prisma version.
My prisma version is: prisma/1.22.1 (darwin-x64) node-v11.2.0

Can you provide me with your prisma version and try this on the latest version.

One odd thing I have noticed is that even though it works on the latest version it still generates it of type `[DateTime!]!` instead of `[DateTime]!`. Maybe this is another bug.


![image](https://user-images.githubusercontent.com/22195362/49646345-c5ea8000-fa44-11e8-8da9-9339a4b851cd.png)

**Comment by Huvik** [comment]
I updated the issue, with a new information and it a little bit changed.

**Comment by MohamedHajr** [comment]
I have this data model

`type Job {
    id: ID! @unique
    createdAt: DateTime!
    date: DateTime!
    description: String!
    url: String! @unique
    title: String!
    employer: String!
    logo: String
    tags: [String!]!
}
```
version: '3'
services:
    prisma:
        image: prismagraphql/prisma:1.22
        restart: always
        ports:
            - '4466:4466'
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                  default:
                    connector: postgres
                    host: example.rds.amazonaws.com
                    port: 5432
                    database: jobs_db
                    schema: jobs
                    user: root
                    password: *****
                    migrations: false
                    ssl: false
```

The same model used to work just fine when i had mysql instead of postgres and after changing to postgres it started to give me this error

Errors:

  Job
    ✖ The scalar field `tags` has the wrong format: `[String!]!` Possible Formats: `String`, `String!`
