### ISSUE TITLE
CLI output for post-deploy hooks is a bit confusing

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma1#4020]
Asume I have these post-deploy hooks in my prisma.yml:

```yml
hooks:
  post-deploy:
    - prisma generate
    - npx nexus-prisma-generate ./src/generated/prisma-client ./src/generated/nexus-prisma 
```

When invoked, the CLI output will be similar to this:

```
Running prisma generate...
Saving Prisma Client (TypeScript) at /Users/nikolasburk/prisma/github/prisma-examples/typescript/graphql/src/generated/prisma-client/
Running prisma generate ✔

Running npx nexus-prisma-generate ./src/generated/prisma-client ./src/generated/nexus-prisma...
ERROR: Missing or invalid argument --client
Running npx nexus-prisma-generate ./src/generated/prisma-client ./src/generated/nexus-prisma ✖
```

In general I think the idea of having start- and end-"checkpoints" make a lot of sense. But the way it's laid out at the moment is a bit confusing because the important information (i.e. the `...` and the ` ✔`) are at the _end_ of the lines, the beginning and the rest of the line look exactly the same. For the longest time I've thought this was a bug that would print the command twice until I realized that the end was different.

So my suggestion is to adjust the wording of the checkpoints to make it clear from the beginning what these messages are about.
