### ISSUE TITLE
Prisma introspect without interactive mode

### ISSUE THREAD

**Issue by marticrespi** [prisma/prisma1#4100]
I want to know if when some bugs about introspection are fixed, we will have available prisma introspect function without interaction as before (now with or without `-i` always pop up interaction mode), because if you want to automate some processes on server side, it's impossible to do any interaction with.

**Comment by divyenduz** [comment]
For non-interactive introspection in SQL connectors, Prisma relies on the `executeRaw` mutation which is available when the underlying server is started [with `rawAccess: true` option](https://www.prisma.io/docs/prisma-graphql-api/reference/raw-database-access-qwe4/#examples). 

Can you confirm that? cc @marticrespi 

Note that 1-click Heroku deployments from Prisma cloud start with `rawAccess: false` and this issue has a workaround for changing that: https://github.com/prisma/prisma-cloud-feedback/issues/233

I will keep this issue open to discuss making this workflow better.

Also see: https://github.com/prisma/prisma-content-feedback/issues/65

**Comment by marticrespi** [comment]
Hi @divyenduz 

Here is my `docker-compose.yml` file

````
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
    - "${PRISMA_MAIN_PORT}:${PRISMA_MAIN_PORT}"
    environment:
      env_file: .env
      PRISMA_CONFIG: |
        port: ${PRISMA_MAIN_PORT}
        managementApiSecret: ${PRISMA_MANAGEMENT_API_JWT_SECRET}
        databases:
          default:
            connector: ${PRISMA_CONNECTOR}
            host: ${PRISMA_HOST}
            database: ${PRISMA_DB_NAME}
            schema: ${PRISMA_DB_SCHEMA}
            user: ${PRISMA_DB_USER}
            password: ${PRISMA_DB_PASSWORD}
            rawAccess: ${PRISMA_DB_RAWACCESS}
            port: ${PRISMA_DB_PORT}
            # If false, prisma doesn't make changes in BBDD, if true, it will make changes from datamodel.prisma
            migrations: ${PRISMA_DB_ALLOW_MIGRATIONS}
            ssl: ${PRISMA_DB_SSL}
      
````

And in a `.env` file I have the rawAccess property setted to `true`.


````
PRISMA_MANAGEMENT_API_JWT_SECRET="my-secret"
PRISMA_DB_PORT=5432
PRISMA_MAIN_PORT=4467
PRISMA_CONNECTOR="postgres"
PRISMA_HOST="someurl.database.azure.com"
PRISMA_DB_NAME="postgres"
PRISMA_DB_SCHEMA="billing"
PRISMA_DB_USER="postgres"
PRISMA_DB_PASSWORD="XXXXXXXXXXXXXXXX"
PRISMA_DB_RAWACCESS=true
PRISMA_DB_ALLOW_MIGRATIONS=false
PRISMA_DB_SSL=true
````

And I deploy it without any problem through a npm script

`    "docker-compose-prod": "cp ./env/prod.env ./.env && docker-compose up -d && sleep 1 && rm ./.env",`

If I execute `prisma introspect` (wihout -i option). DEBUG="*" included:

````
prisma introspect
  client introspecting { serviceName: 'default',
  stageName: 'default',
  workspaceSlug: null } +0ms
TypeError: Cannot read property 'request' of undefined
    at PrismaDBClient.<anonymous> (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\src\databases\prisma\prismaDBClient.ts:71:8)
    at step (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:32:23)
    at Object.next (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:13:53)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:3:12)
    at PrismaDBClient.setDatabaseType (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:114:16)
    at PrismaDBClient.<anonymous> (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\src\databases\prisma\prismaDBClient.ts:110:16)
    at step (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:32:23)
    at Object.next (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:13:53)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:3:12)
    at PrismaDBClient.connect (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\prisma\prismaDBClient.js:160:16)
    at IntrospectCommand.<anonymous> (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-cli-core\src\commands\introspect\introspect.ts:290:18)
    at step (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-cli-core\dist\commands\introspect\introspect.js:45:23)
    at Object.next (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-cli-core\dist\commands\introspect\introspect.js:26:53)
    at fulfilled (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-cli-core\dist\commands\introspect\introspect.js:17:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  util timed out +0ms
Exiting with code: 0
````

Only works with `-i` option. I'm using `prisma/1.29.0-alpha.7` because last official version has a bug getting and declaring arrays related here https://github.com/prisma/prisma/issues/4095.

Thanks!
