### ISSUE TITLE
Foreign key constraint to same table in existing Postgres causing errors on query and create

### ISSUE THREAD

**Issue by rhythnic** [prisma/prisma1#4204]
When Prisma is deployed to an existing Postgres instance in which a table has a field that has a foreign key constraint to the same table's ID field, some records are returned as null in the query result, and creating a record results in 2 records being inserted.  These bugs go away when the foreign key constraint is removed from the SQL file used to create the Postgres instance.

## To reproduce
Use this SQL to restore a new Postgres instance.

```
CREATE TABLE public."networkProtocols" (
    id INT NOT NULL,
    name text,
    "protocolHandler" text,
    "networkTypeId" INT,
    "networkProtocolVersion" text,
    "masterProtocol" INT
);

ALTER TABLE public."networkProtocols" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."networkProtocols_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."networkTypes" (
    id INT NOT NULL,
    name text
);

ALTER TABLE public."networkTypes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."networkTypes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

COPY public."networkProtocols" (id, name, "protocolHandler", "networkTypeId", "networkProtocolVersion", "masterProtocol") FROM stdin;
1	LoRa Server	LoRaOpenSource_1.js	1	1.0	1
2	LoRa Server	LoRaOpenSource_2.js	1	2.0	1
3	The Things Network	TheThingsNetwork.js	1	2.0	3
\.

COPY public."networkTypes" (id, name) FROM stdin;
1	LoRa
\.

SELECT pg_catalog.setval('public."networkProtocols_id_seq"', 4, false);

SELECT pg_catalog.setval('public."networkTypes_id_seq"', 2, false);

ALTER TABLE ONLY public."networkProtocols"
    ADD CONSTRAINT "networkProtocols_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."networkTypes"
    ADD CONSTRAINT "networkTypes_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."networkProtocols"
    ADD CONSTRAINT "networkProtocols_masterProtocol_fkey" FOREIGN KEY ("masterProtocol") REFERENCES public."networkProtocols"(id) ON DELETE SET NULL;

ALTER TABLE ONLY public."networkProtocols"
    ADD CONSTRAINT "networkProtocols_networkTypeId_fkey" FOREIGN KEY ("networkTypeId") REFERENCES public."networkTypes"(id);

```

Deploy this datamodel.
```
type NetworkType @pgTable(name: "networkTypes") {
  id: Int! @unique
  name: String! @unique
  networkProtocols: [NetworkProtocol] @relation(name: "NetworkTypeNetworkProtocols")
}

type NetworkProtocol @pgTable(name: "networkProtocols") {
  id: Int! @unique
  name: String
  protocolHandler: String @unique
  networkType: NetworkType! @pgRelation(column: "networkTypeId") @relation(name: "NetworkTypeNetworkProtocols")
  networkProtocolVersion: String
  masterProtocol: NetworkProtocol @pgRelation(column: "masterProtocol") @relation(name: "MasterProtocolNetworkProtocols")
  networkProtocols: [NetworkProtocol] @relation(name: "MasterProtocolNetworkProtocols")
}
```

Query all NetworkProtocols.

```
query NetworkProtocols {
  networkProtocols {
    id
    name
    networkType {
      id
    }
  }
}
```

The second record is null in the result set.  When the SQL is changed so that the second NetworkProtocol record references itself in the masterProtocol field, it is not null in the query result.

Create a NetworkProtocol.

```
mutation CreateNetworkProtocol {
  createNetworkProtocol(data:{
    name:"LoRa Server",
    protocolHandler:"LoRaOpenSource_3.js",
    networkType:{connect:{id:1}},
    networkProtocolVersion:"3.0"
  }) {
  id
  }
}
```

Two records are created in the table.  The first record created has the primitive values, and the second record has the relationship references.  The masterProtocol field in the second record has the first created record ID as it's value.

```
prisma=# select * from "networkProtocols";
 id |        name        |   protocolHandler   | networkTypeId | networkProtocolVersion | masterProtocol 
----+--------------------+---------------------+---------------+------------------------+----------------
  1 | LoRa Server        | LoRaOpenSource_1.js |             1 | 1.0                    |              1
  2 | LoRa Server        | LoRaOpenSource_2.js |             1 | 2.0                    |              1
  3 | The Things Network | TheThingsNetwork.js |             1 | 2.0                    |              3
  4 | LoRa Server        | LoRaOpenSource_3.js |               | 3.0                    |               
  5 |                    |                     |             1 |                        |              4
(5 rows)

```

**Versions (please complete the following information):**
 - Connector: Postgres
 - Postgres: 10.3
 - Prisma Server: 1.28
 - `prisma` CLI: prisma/1.28.4 (linux-x64) node-v10.15.3
 - OS: Ubuntu 18.04.2

**docker-compose.yml**
```
version: '3.5'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    container_name: dev_lpwanserver_prisma
    networks:
      - lpwanserver_net
    ports:
    - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            database: prisma
            schema: public
            user: prisma
            password: prisma
            rawAccess: true
            port: '5432'
            migrations: false
  postgres:
    image: postgres:10.3
    container_name: dev_lpwanserver_postgres
    networks:
      - lpwanserver_net
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - lpwanserver_postgres:/var/lib/postgresql/data
volumes:
  lpwanserver_postgres:
networks:
  lpwanserver_net:
    name: lpwanserver_net
```
