### ISSUE TITLE
Error relation "default$default.user" does not exist. Existing pgsql db

### ISSUE THREAD

**Issue by SawasReaper** [prisma/prisma1#4278]
Hi, I try to run prisma on my existing postgres db, but after few hours I'm in same buggy spot. I have `public schema` in db but prisma try to resolve queries on `default$default`. 

My docker-compose.yml
```
version: "3.6"

services:
  offhub_pgsql:
    image: postgres:9.6.6-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment: 
      POSTGRES_USER: offhub
      POSTGRES_PASSWORD: offhub
      POSTGRES_DB: offhub
    ports:
      - 5432:5432

  offhub_backend:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - offhub_pgsql
    ports:
      - 9229:9229

  offhub_nginx:
    build:
      dockerfile: Dockerfile
      context: nginx/
    ports:
      - 3030:80
    depends_on:
      - offhub_backend

  prisma:
    image: prismagraphql/prisma:1.29.2
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal 
            database: offhub
            user: offhub
            password: offhub
            rawAccess: true
            port: '5432'
            migrations: false

volumes:
  postgres:
```
My prisma.yml 
Btw I think there is another issue. I can't do `prisma deploy` if it's not on localhost `http://localhost:4466`

```
endpoint: http://host.docker.internal:4466
datamodel: datamodel.prisma

generate:
  - generator: typescript-client
    output: ./generated/prisma-client/
```

I've also tried just with simple model from db: 
```
type User @pgTable(name: "user") {
  id: UUID! @unique
  name: String
}
```
and behaviour is still same.

I've tried quering by playground and with express by adding:
```
import { prisma } from "../../prisma/generated/prisma-client"

// A `main` function so that we can use async/await
async function main() {
    // Create a new user called `Alice`
    const newUser = await prisma.createUser({ name: "Alice" })
    console.log(`Created new user: ${newUser.name} (ID: ${newUser.id})`)

    // Read all users from the database and print them to the console
    const allUsers = await prisma.users()
    console.log(allUsers)
}

main().catch(e => console.error(e))
```

Postgres logs: 
<img width="582" alt="Screenshot 2019-03-29 at 13 59 21" src="https://user-images.githubusercontent.com/22744971/55234319-32270480-522b-11e9-8620-ca9ab86caba3.png">

Prisma logs: 
<img width="1233" alt="Screenshot 2019-03-29 at 13 59 52" src="https://user-images.githubusercontent.com/22744971/55234321-32bf9b00-522b-11e9-9b32-8144c0d45b59.png">

Express logs: 
<img width="1078" alt="Screenshot 2019-03-29 at 14 00 11" src="https://user-images.githubusercontent.com/22744971/55234322-32bf9b00-522b-11e9-8c9b-bdba897fc887.png">

When I've tried this config on empty db with `migrations:true` prisma created default$default schema and everything seem to work fine but it isn't behaviour that I'm looking for.

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.29.2`
 - `prisma` CLI: `prisma/1.29.1 (darwin-x64) node-v10.15.1`
 - OS: `OS X High Sierra` 
 - other dependencies: `prisma-client`

thx for help 😄
