### ISSUE TITLE
Prisma init generates incorrect docker-compose file for mongodb

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#4363]
**Describe the bug**
`prisma init` workflow with existing mongo yields an incorrect docker file with a field called `schema` but it should be named database. 

**To Reproduce**
1. Try `prisma init` on existing mongodb with any database and observe the generated docker file. 
2. Try to use `docker-compose -up -d` and the server will go into a restart loop with: `"Exception in thread "main" java.lang.RuntimeException: Unable to load Pri│ sma config: com.prisma.config.InvalidConfiguration: Expected host to be n│ on-empty"`

**Expected behavior**
Prisma init workflow should generate a correct `docker-compose.yml` file. 

**Versions (please complete the following information):**
 - Connector: `MongoDB`
 - Prisma Server: `1.30`
 - `prisma` CLI: `1.30`

**Additional context:**
Omitting the `database` field also works if the database name is present in connection string, which relates this issue to https://github.com/prisma/prisma/issues/4360

**Comment by divyenduz** [comment]
Related to https://github.com/prisma/prisma/issues/4434

**Comment by kwoxer** [comment]
For me all the ideas to fix it did not help out:
- remove schema
- rename schema to database

Maybe you have tips to me:
- prisma 1.34
- Windows latest docker desktop

yml:
```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: 'mongodb://localhost:27017/admin'
```

Prisma deploy:
```
prisma deploy
 !    Could not connect to server at http://localhost:4466. Please check if your server is running.
```

docker compose logs:

> prisma_1  | Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Expected host to be non-empty
> prisma_1  |     at scala.sys.package$.error(package.scala:26)
> prisma_1  |     at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:40)
> prisma_1  |     at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:48)
> prisma_1  |     at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:13)
> prisma_1  |     at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:8)
> prisma_1  |     at scala.Function0.apply$mcV$sp(Function0.scala:34)
> prisma_1  |     at scala.Function0.apply$mcV$sp$(Function0.scala:34)
> prisma_1  |     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
> prisma_1  |     at scala.App.$anonfun$main$1$adapted(App.scala:76)
> prisma_1  |     at scala.collection.immutable.List.foreach(List.scala:388)
> prisma_1  |     at scala.App.main(App.scala:76)
> prisma_1  |     at scala.App.main$(App.scala:74)
> prisma_1  |     at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:8)
> prisma_1  |     at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala)
