### ISSUE TITLE
Go client - Undefined Uuid

### ISSUE THREAD

**Issue by kevinwmiller** [prisma/prisma1#4438]
**Describe the bug**
Using the UUID type for the id field in datamodel.prisma causes an error when compiling the Go client.
```bash
prisma-client/prisma.go:281:6: undefined: Uuid
```
It seems the issue is there is no scalar mapping for the Uuid type. Should there be a mapping from UUID to 'string', similar to the mapping for the ID type? If so, it looks like this mapping is also missing from the typescript generator.
```go
// cli/packages/prisma-client-lib/src/codegen/generators/go-client.ts
scalarMapping = {
    Int: 'int32',
    String: 'string',
    ID: 'string',
    Float: 'float64',
    Boolean: 'bool',
    DateTime: 'string',
    Json: 'map[string]interface{}',
    Long: 'int64',
}
```
**To Reproduce**
1. Tell prisma to generate the Go client and use datamodel.prisma (Or whatever your datamodel file is called)
```yaml
# Defines your models, each model is mapped to the database as a table.
datamodel: datamodel.prisma

# Specifies the language and directory for the generated Prisma client.
generate:
  - generator: go-client
    output: ../prisma-client/
```
2. Add the following to datamodel.prisma
```graphql
type SomeType {
  id: UUID! @unique
  name: String!
}
```
3. Generate the client code
```bash
prisma generate
```
4. Attempt to compile the go client
```bash
go build -v ./...
```
5. Should receive the error "prisma-client/prisma.go:281:6: undefined: Uuid"

**Expected behavior**
The generator should either map UUID to a string or define the Uuid type in the Go client

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.24.0 (Will update soon
 - `prisma` CLI: 1.31.0
 - OS: Antergos

**Additional context**
I'm connecting to an existing postgres database for SQL migrations (At least until Prisma 2 is finished), and I can't find a way to default row IDs to a CUID in postgres, and I don't want to use sequential IDs for the primary key of each table
