### ISSUE TITLE
Prisma configuration is not very nice to work with

### ISSUE THREAD

**Issue by Bram-Zijp** [prisma/prisma1#4580]
**Is your feature request related to a problem? Please describe.**
One of the things that has costed me much time is the way how the connection yaml configuration is implemented. Currently Prisma offers you to use an PRISMA_CONFIG environment variable which expects an yaml **string**. It is common practice to use environment variables for database credentials. Setting single environment variables is simple in most architectures. In Kubernetes for example you are able to map secrets to environment variables. 

**Describe the solution you'd like**
Allow credentials to be defined on single environment variables e.g.:

PRISMA_MANAGEMENT_API_SECRET='secret'
PRISMA_SQL_USER='username'
PRISMA_SQL_PASSWORD='password'

You could use these environment variables to overwrite the PRISMA_CONFIG in your implementation.

**Additional context**
I found multiple issue reports about this problem.

Edit: Thinking about it longer, it will likely be useful to users to also be able to define variables like port and host through single environment variables.

**Comment by Bram-Zijp** [comment]
If anyone stumbled upon this post and has the same struggle in his Kubernetes environment, here's an hacky example of how I currently inject secrets into the Prisma configuration.

```
# file: ./kubernetes/prisma/prisma.configmap.sh
chmod 600 ./kubernetes/prisma/prisma.configmap.yml
rm ./kubernetes/build/prisma.configmap.yml
cp ./kubernetes/prisma/prisma.configmap.yml ./kubernetes/build/prisma.configmap.yml
sed -i s/REPLACED_PROJECT_NAME_PG_USER/$(kubectl get secret postgres.project-name.credentials -o 'jsonpath={.data.username}' | base64 --decode)/g ./kubernetes/build/prisma.configmap.yml
sed -i s/REPLACED_PROJECT_NAME_PG_PASSWORD/$(kubectl get secret postgres.project-name.credentials -o 'jsonpath={.data.password}' | base64 --decode)/g ./kubernetes/build/prisma.configmap.yml
cat ./kubernetes/build/prisma.configmap.yml


# file: ./kubernetes/prisma/prisma.configmap.sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  namespace: default
  labels:
    stage: production
    name: prisma
    app: prisma
data:
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: postgres
        host: hostname
        database: cms
        rawAccess: true
        port: 5432
        migrations: true
        user: REPLACED_PROJECT_NAME_PG_USER
        password: REPLACED_PROJECT_NAME_PG_PASSWORD

```
