### ISSUE TITLE
about  Docker image prisma 1.34.10 does not exist  /Usr / share / zoneinfo directory,  User cannot customize time zone!

### ISSUE THREAD

**Issue by CGerAJ** [prisma/prisma1#5048]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Docker image does not exist  /Usr / share / zoneinfo directory,  User cannot customize time zone!

**Describe alternatives you've considered**

Can I get the correct time zone?
```
image: prismagraphql/prisma:1.34.10
    restart: always
    container_name: wanli_server_v5_prisma_server
    ports:
      - '4465:4466'
    environment:
      TZ: Asia/Shanghai  #There is no / usr / share / zoneinfo directory in the container
```

**Additional context**
![image](https://user-images.githubusercontent.com/20548301/77025397-ef29e800-69cb-11ea-8b23-f637668128ce.png)
