### ISSUE TITLE
Connection error: org.postgresql.util.PSQLException: ERROR: unsupported startup parameter: search_path

### ISSUE THREAD

**Issue by oem2** [prisma/prisma1#5051]
**Describe the bug**
I get the following error when setting up my Prisma instance:

```
Mar 25, 2020 5:00:56 AM org.postgresql.Driver connect
prisma_1    | SEVERE: Connection error: 
prisma_1    | org.postgresql.util.PSQLException: ERROR: unsupported startup parameter: search_path
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
prisma_1    | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1    | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1    | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1    | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1    | 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
```

I am running a managed PostgreSQL database on Digital Ocean. My docker-compose.yaml file looks like this:

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.14
    restart: always
    ports:
    - "4466:4466"
    environment:
      IGNORE_STARTUP_PARAMETERS: search_path , extra_float_digits
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: postgres
            ssl: true
            host: xxxxxxxxx
            port: 25061
            user: prisma
            schema: public
            password: xxxxxxxxx
            migrations: true
            managementSchema: management
            database: xxxxxxx
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: xxxxxxx
      POSTGRES_PASSWORD: xxxxxxxxx
      IGNORE_STARTUP_PARAMETERS: search_path , extra_float_digits
```
