### ISSUE TITLE
Unable to load Prisma config: mapping values are not allowed here  in 'string', line 2, column 5: port: 4466

### ISSUE THREAD

**Issue by 5achinJani** [prisma/prisma1#5064]
**Describe the bug**
Everything was running fine so far. outta nowhere we're facing this issue where prisma image fails in docker.

**To Reproduce**
1. docker-compose up -d

**Screenshots**
![image](https://user-images.githubusercontent.com/23077544/78376644-3a5b1200-75ec-11ea-8153-b26945dc9f83.png)

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: [e.g. `1.34.0`]
 - `prisma` CLI: [e.g. `prisma/1.34.0 
 - OS: `Windows 10`
- Docker Desktop: 2.2.0.5
- Able to reproduce in the mac system too.

**Additional context**
- docker-compose file(exact same as prisma-examples):
```yml
version: '3'
services:
  prisma:
    env_file: .development.env
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret:${PRISMA_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~

```
Everything was running good so far. I even tried `docker system prune` and then `docker-compose up -d` still the same. 
`docker ps`
![image](https://user-images.githubusercontent.com/23077544/78377117-d4bb5580-75ec-11ea-86fc-d2a104a94810.png)
