### ISSUE TITLE
docker-compose.yml invalid type prisma with mysql connector : 1.34

### ISSUE THREAD

**Issue by TachafineAITTouda** [prisma/prisma1#5071]
after prisma init i chosed a local Mysql MAMP/XAMP server localhost and the user plus the password, but i had one empty database in the mysql server `graphdb` , so the CLI didn't ask me about the database i will be using.
after that it generated the `docker-compose.yml` file for me, i didn't touch it. 

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4467:4467"
    environment:
      PRISMA_CONFIG:  |
        port: 4467
        databases:
          default:
            connector: mysql
            host: host.docker.internal
            schema: testdb
            user: root
            password: password
            rawAccess: true
            port: '3306'
            migrations: true
```

and after i run the `docker-compose.yml run -d` it works. 
but when i check the 'docker ps' i find that the server is restarting all the time 
then i logged it and found this 
```
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Only Postgres connectors specify a schema
```
and since MariaDB doesn't use schema concepts, so i tried changing shema with database and it worked  
```
    environment:
      PRISMA_CONFIG:  |
        port: 4467
        databases:
          default:
            connector: mysql
            host: host.docker.internal
            database: testdb
            user: root
            password: password
            rawAccess: true
            port: '3306'
            migrations: true
```

**Versions (please complete the following information):**
 - Connector: [ `MySQL`]
 - Prisma Server: [e.g. `1.34.0`]
 - `prisma` CLI: [`prisma/1.24.0 (darwin-x64) node-v10.4.0`]
 - OS: [ `Windows 10`]
