### ISSUE TITLE
Prisma Subscription Request From Playground Returns Error

### ISSUE THREAD

**Issue by technicallynick** [prisma/prisma1#5072]
**Describe the bug**
Any attempt to test a subscription directly to the Prisma server via Playground returns the following error: 

> The provided query doesn't include any known model name. Please check for the latest subscriptions API.

In review of the WS transactions in the browser console, I can see I am receiving this response from the Prisma endpoint, but nothing is being logged by Prisma in docker. 

I posted a question in [Slack](https://prisma.slack.com/archives/CA491RJH0/p1586541306463900) and on [StackOverflow](https://stackoverflow.com/questions/61194842/prisma-subscription-request-from-playground-returns-error), but no one has responded to either query. 
**docker-compose.yml**
```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4465:4465'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4465
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: ${POSTGRESS_PASS}
            rawAccess: true
  postgres:
    image: postgres:10.3
    restart: always
    ports:
       - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: ${POSTGRESS_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
```

**To Reproduce**
1. Create a local instance of Prisma1 in docker
2. Create a datamodel with at least one data type that can be subscribed to and deploy
3. Open `prisma playground`
4. Send basic subscription request such as
```graphql
subscription CHAT {
  dMEntry {
    mutation
    updatedFields
  }
}
```
5. Witness error returned in playground.

**Expected behavior**
When I make a request directly to the Prisma database using the model supplied to me by the docs tab, I expect the results tab to be "Listening..."

**Screenshots**
![Subscription_Error](https://user-images.githubusercontent.com/24781863/79362014-e3faa700-7efa-11ea-9786-e1abb5c0823d.png)

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.34.10
 - `prisma` CLI: prisma/1.34.10 (linux-x64) node-v12.13.1
 - OS: Prisma Server running on Debian 10, Prisma Playground(client) running on Mac OS (10.15.4) from Chrome 80

**Comment by nikolasburk** [comment]
Hey @technicallynick, thanks a lot for opening this issue! I tried reproducing your problem but for me everything worked (I basically followed the "Get started" tutorial and after having deployed the datamodel with `User` and `Post` my subscription is working).

![image](https://user-images.githubusercontent.com/4058327/80121155-3d627600-858c-11ea-9d50-04ba950e4a30.png)
 
![image](https://user-images.githubusercontent.com/4058327/80121148-3b001c00-858c-11ea-979c-df670917dff4.png)

My Docker Compose file:  

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4465:4465'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4465
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: ${POSTGRESS_PASS}
            rawAccess: true
  postgres:
    image: postgres:10.3
    restart: always
    ports:
       - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: ${POSTGRESS_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
```

And Prisma datamodel:

```graphql
type User {
  id: ID! @id
  email: String @unique
  name: String!
  posts: [Post!]!
}

type Post {
  id: ID! @id
  title: String!
  published: Boolean! @default(value: false)
  author: User @relation(link: INLINE)
}
```

And prisma.yml:

```yml
endpoint: http://localhost:4465
datamodel: datamodel.prisma
```

Can you reproduce this problem in a fresh project as well by following the same tutorial or does this not work either when you set up a new project from scratch?
