### ISSUE TITLE
Stream subscription events

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#585]
Additionally to invoking functions via subscription events, it would be great if subscription events could be streamed directly to different event targets such as AWS Kinesis, Kafka etc.

Until this feature is directly supported via Graphcool, an easy workaround is to use functions and forward events programatically.

**Comment by sorenbs** [comment]
We have decided to remove the top-level `functions` field. See #591

If sendConfirmEmail is a subscription that should put an item on a kinesis queue it should look like this:

```yml
subscriptions:
  sendConfirmEmail:
    handler:
      kinesis:
        stream: my-kinesis-stream
    query: ./src/sendConfirmEmail.graphql
```
